pol/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import HomepageView

urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^poll/', include('poll.urls')),
    url(r'^registration/', include('registration.urls')),
]

poll/urls.py
from django.conf.urls import url
from . import views

app_name = 'poll'

urlpatterns = [

    # /poll/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /poll/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /poll/desc-6/
    url(r'^choice-(?P<pk>[0-9]+)/$',
        views.DescriptionView.as_view(), name='description'),

    # /poll/5/vote/
    url(r'^(?P<topic_id>[0-9]+)/vote/$',
        views.VoteView.as_view(), name='vote'),


    # /poll/desc-6/
    url(r'^d-(?P<choice_id>[0-9]+)/comment$',
        views.AddCommentView.as_view(), name='comment'),

    # /poll/add/
    url(r'^add/$', views.AddView.as_view(), name='add'),

]

registration/urls.py
from django.conf.urls import url
# from django.contrib.auth import views as auth_views

from . import views

app_name = 'registration'

urlpatterns = [
    url(r'^sign-in/$', views.SignInView.as_view(), name='sign_in'),
    url(r'^sign-up/$', views.SignUpView.as_view(), name='sign_up'),
    url(r'^sign-out/$', views.SignOutView.as_view(), name='sign_out'),
]

poll/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    topic_text = models.CharField(max_length=150)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date added')

    def __str__(self):
        return self.topic_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=150)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date added')

    def __str__(self):
        return self.choice_text


class Comment(models.Model):
    comment_text = models.CharField(max_length=1000)
    type = models.IntegerField(default=0)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date added')

    def __str__(self):
        return self.comment_text


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    def __str__(self):
        return self.topic + ' - ' + self.user

pol/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from django.contrib.auth.mixins import LoginRequiredMixin


class HomepageView(LoginRequiredMixin, TemplateView):
    login_url = 'registration:sign_in'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        return HttpResponseRedirect(reverse('poll:index'))

poll/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Topic, Choice, Comment, Vote


class IndexView(LoginRequiredMixin, generic.ListView):
    """View for showing choices all polls"""
    login_url = 'registration:sign_in'
    redirect_field_name = 'redirect_to'

    template_name = 'poll/index.html'
    context_object_name = 'topic_list'

    def get_queryset(self):
        """Returns all polls, ordered by date"""
        return Topic.objects.order_by('-pub_date')


class DetailView(LoginRequiredMixin, generic.DetailView):
    """View for showing choices in a respective poll"""
    login_url = 'registration:sign_in'
    redirect_field_name = 'redirect_to'

    model = Topic
    template_name = 'poll/detail.html'


class DescriptionView(LoginRequiredMixin, generic.DetailView):
    """View for poll choice description (which shows comments)"""
    login_url = 'registration:sign_in'
    redirect_field_name = 'redirect_to'

    model = Choice
    template_name = 'poll/description.html'

    def get_context_data(self, **kwargs):
        """Returns pro and con comments"""

        context = super(DescriptionView, self).get_context_data(**kwargs)
        pro = Comment.objects.filter(type=1, choice=self.kwargs['pk'])
        con = Comment.objects.filter(type=-1, choice=self.kwargs['pk'])

        context['pro_comments'] = pro
        context['con_comments'] = con
        return context


class AddView(LoginRequiredMixin, generic.View):
    """View for adding new poll"""
    login_url = 'registration:sign_in'
    redirect_field_name = 'redirect_to'
    template_name = 'poll/add_poll.html'

    def get(self, request):
        """Returns a form to add new poll"""
        context = {}
        return render(request, self.template_name, context=context)

    def post(self, request):
        """Saves new poll data to database, then redirects to index page"""
        new_topic = Topic(topic_text=request.POST['topic_text'],
                          user=request.user, pub_date=timezone.now())
        new_topic.save()

        i = 1
        while('choice_' + str(i) in request.POST):
            choice = 'choice_' + str(i)
            if request.POST[choice] != '':

                new_choice = Choice(choice_text=request.POST[choice],
                                    topic=new_topic, user=request.user,
                                    pub_date=timezone.now())
                new_choice.save()
            i += 1

        return HttpResponseRedirect(reverse('poll:index'))


class VoteView(LoginRequiredMixin, generic.View):
    """View for voting"""
    login_url = 'registration:sign_in'
    redirect_field_name = 'redirect_to'

    def post(self, request, topic_id):
        """Increments vote based on user's choice. Otherwise, returns error"""

        topic = get_object_or_404(Topic, pk=topic_id)

        poll_vote = Vote.objects.filter(user=request.user, topic=topic)

        if poll_vote.exists():
            return render(request, 'poll/detail.html', {
                'topic': topic,
                'error_message': "You've already voted.",
            })

        try:
            selected_choice = topic.choice_set.get(id=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'poll/detail.html', {
                'topic': topic,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            new_vote = Vote(user=request.user, topic=topic)
            new_vote.save()

            return HttpResponseRedirect(reverse('poll:detail',
                                        args=(topic.id,)))


class AddCommentView(LoginRequiredMixin, generic.View):
    """View for adding comments"""
    login_url = 'registration:sign_in'
    redirect_field_name = 'redirect_to'

    def post(self, request, choice_id):
        """When successful, saves comment to database and return success status.
           Otherwise, return failed status"""
        choice = get_object_or_404(Choice, pk=choice_id)
        # if request.POST['comment_text'] == '':
        #     return JsonResponse({'status': 'failed'})
        new_comment = Comment(comment_text=request.POST['comment_text'],
                              type=request.POST['type'], choice=choice,
                              user=request.user, pub_date=timezone.now())
        new_comment.save()

        return JsonResponse({'status': 'success',
                             'comment_text': new_comment.comment_text,
                             'comment_user': new_comment.user.username,
                             'pub_date': new_comment.pub_date})

poll/templates/poll/add_poll.html
{% extends 'poll/base.html' %}

{% block body %}
    <div class="form-container">
        <h3>Add new poll</h3>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'poll:add' %}" method="post" id="#add_poll">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="topic_text" placeholder="Topic" class="form-control" autocomplete="off">
            </div>
            <div id="choice_container" class="choice_container">
                <div class="form-group"><input type="text" name="choice_1" placeholder="Choice 1" class="form-control" autocomplete="off" id="choice"></div>
                <div class="form-group"><input type="text" name="choice_2" placeholder="Choice 2" class="form-control" autocomplete="off" id="choice"></div>
            </div>
            <button type="button" class="button-generic" onclick="appendChoiceField()">Add Choice</button>
            <button type="button" class="button-generic" onclick="removeChoiceField()">Remove Choice</button>
            <button class="button-main" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

poll/templates/poll/base.html
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'poll/css/styles.css' %}" />
        <title>Brand Pit</title>
    </head>
    <body>
        <div class="header">
            <img class="logo" />
                <ul class="nav-bar">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'poll:index' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'poll:add' %}">Add+</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration:sign_out' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration:sign_up' %}">Sign up</a>
                        </li>
                    {% endif %}
                </ul>
        </div>
        {% block  body %}
        {% endblock %}
        <script src= "{% static 'poll/js/require.js'%}"></script>
        <script>
            require.config({
                baseUrl: "{% static 'poll/js/' %}",
                paths: {
                    'jquery': "{% static 'poll/js/jquery.min' %}"
                }
            });
        </script>
        <script src="{% static 'poll/js/main.js' %}"></script>
    </body>
</html>

poll/templates/poll/description.html
{% extends 'poll/base.html' %}
{% block body %}
    <h1 class="primary-text">{{ choice.choice_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="body-container">
        <div class="comment-container">
            <div class="column-comment-pro" id="pro_comments">
                <h2 class="comment-header">Pros</h2>
                    {% for pro_comment in pro_comments %}
                    <div class="card-comment-pro">
                        <div class="card-comment-content">
                            <p>{{ pro_comment.comment_text }}</p>
                        </div>
                        <div class="card-comment-user">
                            <p>{{ pro_comment.user }}</p>
                        </div>
                        <div class="card-comment-date">
                            <p>{{ pro_comment.pub_date }}</p>
                        </div>
                    </div>
                    {% endfor %}
            </div>
            <div class="column-comment-con" id="con_comments">
                <h2 class="comment-header">Cons</h2>
                    {% for con_comment in con_comments %}
                    <div class="card-comment-con">
                        <div class="card-comment-content">
                            <p>{{ con_comment.comment_text }}</p>
                        </div>
                        <div class="card-comment-user">
                            <p>{{ con_comment.user }}</p>
                        </div>
                        <div class="card-comment-date">
                            <p>{{ con_comment.pub_date }}</p>
                        </div>
                    </div>
                    {% endfor %}
            </div>
        </div>
        <div class="push">
        </div>
    </div>
    <div class="footer">
        <div class="comment-container">
            <div class="column-comment-pro-field">
                    <div class="form-container-comment">
                        <form action="{% url 'poll:comment' choice.id %}" method="post" id="add_comment_pro">
                            {% csrf_token %}
                            <input type="textarea" name="comment_text_pro" id="comment_text_pro" class="form-control" required/><br />
                            <button type="submit" class="button-small-right"><p class="label-button-small">Add comment</p></button>
                        </form>
                    </div>
            </div>
            <div class="column-comment-con-field">
                    <div class="form-container-comment">
                        <form action="{% url 'poll:comment' choice.id %}" method="post" id="add_comment_con">
                            {% csrf_token %}
                            <input type="textarea" name="comment_text_con" id="comment_text_con" class="form-control"  required/><br />
                            <button type="submit" class="button-small-left"><p class="label-button-small">Add comment</p></button>
                        </form>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

poll/templates/poll/detail.html
{% extends 'poll/base.html' %}

{% block body %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'poll:vote' topic.id %}" method="post" id="add_vote">
        {% csrf_token %}
        <div class="card-container">
            {% for choice in topic.choice_set.all %}
                <div class="card-choice">
                    <h3>
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                        <label for="choice{{ forloop.counter }}">
                            {{ choice.choice_text }}
                        </label>
                    </h3>
                    <p class="label">
                        Votes: {{ choice.votes}}
                    </p>
                    <a href="{% url 'poll:description' choice.id %}">
                        <button class="button-small" type="button"><p class="label-button-small">Comments</p></button>
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="button-container">
            <input type="submit" value="Vote" class="button-vote"/>
        </div>
    </form>
{% endblock %}

poll/templates/poll/index.html
{% extends "poll/base.html" %}

{% block body %}
    {% if topic_list %}
        <div class="card-container">
            {% for topic in topic_list %}
            <a href="{% url 'poll:detail' topic.id %}">
                <div class="card-topic">
                    <div class="card-header">
                        {{ topic.topic_text }}
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    {% else %}
        <h1>No polls yet.</h1>
    {% endif %}
{% endblock %}